version: '2'
services:  
  parking-lot-service:
    build: .
    depends_on:
      - parking-lot-postgres
    environment:
      - NODE_ENV=development
      - POSTGRESQL_DATABASE=parking-lot
      - POSTGRESQL_HOST=parking-lot-postgres
      - POSTGRESQL_USER=postgres
      - POSTGRESQL_PASSWORD=postgres
    ports:
      - 3000:3000
    restart: unless-stopped

  parking-lot-postgres:
    image: postgres:12
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=parking-lot
    volumes:
       - ./database-data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    restart: unless-stopped